---
on:
  workflow_dispatch:
    inputs:
      season:
        required: true
        type: number
      grand_prix:
        required: true
        type: string
      is_sprint:
        required: false
        type: boolean
        default: false
    outputs:
      artifact-id:
        description: "The artifact id of the workflow output"
        value: ${{ jobs.run-workflow.outputs.artifact-id }}
      artifact-url:
        description: "The artifact url of the workflow output"
        value: ${{ jobs.run-workflow.outputs.artifact-url }}

jobs:
  run-workflow:
    uses: .github/workflows/download_and_parse.yml
      
